### ISSUE TITLE
Master Measure formatting support

### ISSUE THREAD

**Issue by frankdoom** [GINQO/Master-Item-Manager#17]
Support for exporting and importing Master Measure formatting.
![image](https://user-images.githubusercontent.com/16254298/103904256-53ee3480-50fd-11eb-9b36-edce43f02ef3.png)

**Comment by hgrpixum** [comment]
i have added support for this in my fork: https://github.com/hgrpixum/Master-Item-Manager

**Comment by GINQO** [comment]
Resolved.
