### ISSUE TITLE
Issue with Link Icons

### ISSUE THREAD

**Issue by maxwellginqo** [GINQO/Master-Item-Manager#27]
@rikiginqo 
Icons aren't showing up correctly on bottom panel of Master Item Manager

![image_2022_09_02T21_30_55_453Z](https://user-images.githubusercontent.com/58995836/188238107-f99f5542-d438-4fd8-aa34-2b01d5ecc35c.png)

**Comment by rikiginqo** [comment]
@maxwellginqo 

woff2 font type is not supported in Qlik Sense Enterprise. So, I just added .woff and .tff files under font folder to fix this issue.

**Comment by maxwellginqo** [comment]
@rikiginqo 
Looks like this has corrected this problem. I will close this issue now.

Thank you,
Maxwell.
