### ISSUE TITLE
Synchronize measures

### ISSUE THREAD

**Issue by Over90000000** [GINQO/Master-Item-Manager#29]
Hey

I'm using Qlik Sense Server On-Prem and I would like to import some measures that I previously exported from another app. Unfortunately this does not work. Synchronizing dimensions works. What could be the reason for this? I tried it with the template and a custom Excel, with the same result..

**Comment by maxwellginqo** [comment]
Hi @Over90000000,

Can you provide some information on the version of Qlik Sense you are using?
If you can also provide us with the template file you are using we will take a look right away.

cc'ing
@rikiginqo

**Comment by Over90000000** [comment]
Hey

thanks for the quick reply! I am using Qlik Server version 14.45.4 February 2022 Patch 1. I tried it with the extension from June 2022. As a template I took the deposited Excel from the directory.

**Comment by maxwellginqo** [comment]
@Over90000000, 

Can you please attach the template file with the expressions you are using?
We will do some testing and get back to you about why this is happening.

Thanks,
Maxwell.

**Comment by Over90000000** [comment]
Sure
[Master Item Template File.xlsx](https://github.com/GINQO/Master-Item-Manager/files/9545729/Master.Item.Template.File.xlsx)
I have tried around a bit with the quotation marks, unfortunately without success. With the dimensions everything worked.

Thank you

**Comment by maxwellginqo** [comment]
Thanks for providing the template.

We'll try to have an answer for you by next Friday

@rikiginqo

**Comment by sloboy** [comment]
Try to put values from the template file into your columns for formatting, including thousand and decimal separators.

**Comment by Over90000000** [comment]
Hey,

through the hint I came indirectly to the fact that I load too few columns in the "Measures". I just lazily took the script from the readme. If all columns are loaded it works!

Many thanks and many greetings
