### ISSUE TITLE
Creation of Measures not possible in SaaS

### ISSUE THREAD

**Issue by ChristianPrinz** [GINQO/Master-Item-Manager#30]
Are there currently any known problems with the creation of key figures in the SaaS version?
We are currently not able to create key figures via the extension - but it works without problems for dimensions.

Do you have a solution for me?

Thank you for the great extension! :slightly_smiling_face:

Many greetings
Chris

**Comment by maxwellginqo** [comment]
Hi Christian, can you clarify what you mean by "key figures"?

Do you mean you are having some problems creating measures or that you are having problems creating measures off a key field in the data model?

Regards,
Maxwell.

**Comment by ChristianPrinz** [comment]
Sorry, we had used an older version of import Excel and it was probably no longer usable. 

Issue is therefore resolved - but thanks for the quick feedback!
