### ISSUE TITLE
Master Measures issue in Saas 

### ISSUE THREAD

**Issue by acalez69** [GINQO/Master-Item-Manager#31]
Hi, I'm using the extension (June 2022 build 1.8) in Qlik Sense Saas: Dimensions are created but not the Measures. Clicking on Edit Measures and Syncronize nothing appear and the measures are not created. (In the enterprise version it works without problems)

**Comment by maxwellginqo** [comment]
Hi @acalez69, we will take a look into this issue within the next couple weeks.

@rikiginqo

**Comment by acalez69** [comment]
Hi Max,

Have you had a chance to verify?

Best

**Comment by maxwellginqo** [comment]
Hi Acalez, can you provide the template file you are using? We will start testing this next week

Thanks,
Maxwell.

**Comment by acalez69** [comment]
[Sample_MI_Manager.xlsx](https://github.com/GINQO/Master-Item-Manager/files/10090154/Sample_MI_Manager.xlsx)

Here it is.

I also tried with an InLine load in this way:
  [Measures]:
  Load * Inline [
  %MI%MeasureExpression;	%MI%MeasureName;	%MI%MeasureLabelExpression;	%MI%MeasureDescription;	%MI%MeasureColor;  	%MI%MeasureTags;	%MI%MeasureSegmentColor;%MI%MeasureSegmentColorFormat;	%MI%MeasureId  
 	=Count(Dim1); Misura1; 'MisuraLabel'; 'MisuraDescrizione'; #ff0000 ; 'TAGS MISURA'; ; ; 101](delimiter is ';');

But "Syncronize" doesn't work.

Thank you in advance

Andrea

**Comment by maxwellginqo** [comment]
Great thanks @acalez69. @rikiginqo will take a look at this next weekend.

Regards,
Maxwell.

**Comment by sloboy** [comment]
@acalez69, @rikiginqo @maxwellginqo 
Check that you have all the new columns (mainly formatting, but color too) in the input file.  If you are missing any, it wont make any measures, or the button to make them fails.  Export a blank template from the extension to see the names.

**Comment by maxwellginqo** [comment]
Thanks for the tip @sloboy. 
We are looking to display some indication on the front-end as to why measures might be created incorrectly/not accepted by the MIM. 
Stay in touch!

Maxwell.

**Comment by acalez69** [comment]
Hi All, thank you for the tip but we still have the issue (with the Measures) [Only in Saas edition]
Here below an Example how we tried to fill the different measures attributes.

When we click on "Syncronize" nothing is happening.

Script Sample:

  [Measures]:
  Load * Inline [
  %MI%MeasureName;	%MI%MeasureDescription;	%MI%MeasureExpression;	 %MI%MeasureLabelExpression;	%MI%MeasureColor;	%MI%MeasureTags;	%MI%MeasureSegmentColor;	%MI%MeasureSegmentColorFormat;	%MI%MeasureFormatType;	%MI%MeasureFormatNDec;	%MI%MeasureFormatUseThou;	%MI%MeasureFormatFmt;	%MI%MeasureFormatDec;	%MI%MeasureFormatThou;	%MI%MeasureId;
  Misura1;			Descrizione Misura1;	=count(Dim1);			'# Measure in Value';			#000000;			ExampleMeasure;		;							;								;						;						;							;						;						;						100;			
  ](delimiter is ';');

**Comment by rikiginqo** [comment]
hi @acalez69 @sloboy,

We have identified the issue and we are working to fix it.
A new version will be released in a couple of days.

Thank you
cc: @maxwellginqo

**Comment by maxwellginqo** [comment]
Thanks for the update @rikiginqo

**Comment by acalez69** [comment]
Hi @rikiginqo,

maybe you have a Christmas present for me...? :)

I like very much this extension

Thank you for all your support

**Comment by rikiginqo** [comment]
@acalez69:
Yes, we do.
The updates are now under review.
Anyway, you can test the code if you want and give me some feedback before it is released.

Use this:
https://github.com/rikiginqo/Master-Item-Manager

Thanks,
Riki

**Comment by maxwellginqo** [comment]
Hi @acalez69, Riki has made updates to the Master Item Manager that should correct the synchronization issues you were experiencing. Do you want to give it a try and get back to us?

**Comment by acalez69** [comment]
Hi @maxwellginqo, 
we had a quick test and now it works. 
Thank you very much!!

**Comment by maxwellginqo** [comment]
@acalez69 Fantastic to hear this is working for you!
@rikiginqo nice work.

Will create a new release this afternoon. Closing this case now.
