### ISSUE TITLE
Drill down dimensions break on change/update

### ISSUE THREAD

**Issue by GINQO** [GINQO/Master-Item-Manager#5]
Adding a tag (for example) to an existing/functioning drill-down dimension breaks upon an edit. Converts the dimension from "drill-down" to "single".

![image](https://user-images.githubusercontent.com/40841120/61316305-91e2f480-a7b5-11e9-9f15-49848e96821e.png)

**Comment by martinfcurtis** [comment]
Is there a plan to resolve this issue?

**Comment by maxwellginqo** [comment]
Yes this has been resolved now. Thanks
