### ISSUE TITLE
Is it possible to add more than one tag? Is it it possible to create/update drilldown dimenson?

### ISSUE THREAD

**Issue by caiocaminoski** [GINQO/Master-Item-Manager#6]
The issue I have is similar to issue #5, I cannot add extra labels or manage drill-down dimensions. Is there a separator that I should be adding to create those fields/tags?

Is it in the roadmap for a next release?

Thank you very much for the extension!

Caio

**Comment by maxwellginqo** [comment]
Hi in the new release you can separate tags by a comma to add extra ones. Same goes for Drill-down dimensions.
